language: node_js

node_js:
  - "8"
  - "10"

services:
  - docker

script:
  - docker-compose build --build-arg node_version=${TRAVIS_NODE_VERSION} test
  - docker-compose run test grunt ci

notifications:
  webhooks:
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email:
    recipients:
      - dev@medicmobile.org
