language: node_js

node_js:
  #- "8"
  - "10"
  #- "12"

services:
  - docker
  - postgres
  - couchdb

stage: build
script: docker build -t couch2pg-test-${TRAVIS_BUILD_NUMBER} --network host --target test-couch2pg --build-arg COUCH_ADMIN=${CI_COUCHDB_ADMIN} --build-arg COUCH_PASS=${CI_COUCHDB_PASS} --build-arg PG_PASS="" --build-arg POSTGRES_SVC=localhost --build-arg COUCHDB_SVC=localhost .

stage: deploy
script: docker build -t medicmobile/medic-couch2pg-${TRAVIS_BRANCH} .
script: echo "$CI_DOCKER_PASSWORD" | docker login -u "$CI_DOCKER_USERNAME" --password-stdin
script: docker push medicmobile/medic-couch2pg-${TRAVIS_BRANCH}

notifications:
  webhooks:
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email:
    recipients:
      - dev@medicmobile.org
