version: '3.7'

services:

  couch2pg:
    container_name: medic-couch2pg
    image: medicmobile/couch2pg:3.7.0-test1
    environment:
      - COUCH_URL=
      - COUCH_NODE_NAME=
    volumes:
      - medic-couchconfig:/opt/couchdb/etc/local.d
    networks:
      - medic-net
    depends_on:
      - postgres

# Create postgres with rdbms config
# postgres admin user
  postgres:
    container_name: postgres
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=medic-couch2pg
      - POSTGRES_DB=cht-core
    volumes:
      - medic-rdbms:/var/lib/postgresql/data
      - medic-couchconfig:/opt/couchdb/etc/local.d
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf

volumes:
  medic-rdbms:
    name: medic-rdbms


# TO DO:
# - create postgresql.conf and map it into Postgres container_name
# - Share passwords b/w postgres user and couch2pg container without input
# - Launch compose with medic-os compose and see if it works
# - build, test, node_modules, docker-ignore, travis-ci