version: '3.7'
services:

  postgres:
    image: medicmobile/cht-postgres:release-postgres13-rc.1
    environment:
      POSTGRES_DB: cht
      POSTGRES_USER: cht
      POSTGRES_PASSWORD: cht_password
      COUCH2PG_USER: cht_couch2pg
      COUCH2PG_USER_PASSWORD: couch2pg_password
      DB_OWNER_GROUP: cht_analytics
    volumes:
    - cht-postgres-data:/var/lib/postgresql/data
    networks:
    - cht-net
    ports:
    - ${PG_PORT:-5432}:5432

  cht-couch2pg:
    build:
      context: .
    volumes:
      - ./libs:/usr/app/libs
    environment:
      COUCHDB_URL: ${COUCHDB_URL:-"http://cht:cht-password@couch:5984"}
      POSTGRES_USER_NAME: cht
      POSTGRES_PASSWORD: cht_password
      POSTGRES_DB: postgres
      POSTGRES_DB_NAME: cht

    networks:
      - cht-net
    depends_on:
      - postgres

networks:
  cht-net:
    name: cht-net

volumes:
  cht-postgres-data:
    name: cht-postgres-data
